import type { RhCopyCode, RhCustomerCopy } from "./reportTypes.js";

export const RH_COPY_REGISTRY: Record<RhCopyCode, string> = {
  report_title: "Merchant processing statement review",
  unable_title: "We could not complete a reliable analysis",
  unable_body: "The statement does not provide enough reliable financial information for a safe report.",
  open_title: "Your analysis is ready with questions to resolve",
  open_body: "Confirmed facts are shown below. Conclusions that need more evidence remain clearly withheld.",
  completed_title: "Your statement analysis is complete",
  completed_body: "The available statement evidence supports the financial analysis shown below.",
  comparison_unavailable: "Qualified comparison not available",
  axis_analysis_readiness: "Analysis readiness",
  axis_comparison_position: "Qualified comparison",
  axis_economic_finding: "Economic finding",
  axis_priority: "Priority",
  axis_evidence_strength: "Evidence strength",
  axis_open_questions: "Open questions",
  axis_unavailable: "Unavailable",
  axis_available_with_questions: "Available with questions",
  axis_completed: "Completed",
  axis_needs_confirmation: "Needs confirmation",
  axis_no_attention_proven: "No material attention item proven",
  axis_attention_present: "Attention items present",
  axis_supported_impact: "Supported impact present",
  axis_unresolved_material: "Material items unresolved",
  axis_routine: "Routine",
  axis_review: "Review",
  axis_high_priority: "High priority",
  axis_statement_confirmed: "Statement confirmed",
  axis_deterministically_derived: "Deterministically derived",
  axis_knowledge_supported: "Admitted knowledge supported",
  axis_mixed_supported: "Mixed supported evidence",
  axis_limited: "Limited",
  axis_unresolved: "Unresolved",
  axis_questions_none: "None",
  axis_questions_nonblocking: "Nonblocking",
  axis_questions_material: "Material",
  snapshot_title: "Statement snapshot",
  processed_sales: "Processed sales",
  processing_fees: "Statement-period processing fees",
  effective_rate: "Effective rate",
  transaction_count: "Gross-sale transaction count",
  average_ticket: "Average ticket",
  metric_unavailable: "Not available",
  rate_undefined: "Undefined for this period",
  pricing_title: "Pricing structure",
  pricing_not_confirmed: "Not confirmed",
  pricing_partially_supported: "The statement supports some pricing axes. Unresolved axes remain not confirmed.",
  pricing_axis_confirmed: "Confirmed from admitted canonical evidence.",
  pricing_axis_not_confirmed: "Not confirmed from the available admitted evidence.",
  pricing_axis_unknown: "Unknown because the available admitted evidence does not establish this axis.",
  pricing_axis_unresolved: "Unresolved because the required admitted evidence or coverage is incomplete.",
  pricing_axis_unavailable: "Unavailable from this statement and the currently admitted evidence.",
  pricing_axis_not_applicable: "Not applicable because admitted evidence proves there was no active processing.",
  pricing_supported_summary: "The statement supports the pricing structure shown below.",
  pricing_underlying_cost: "Underlying-cost billing",
  pricing_schedule: "Merchant price schedule",
  pricing_scope: "Scope uniformity",
  pricing_cost_pass_through: "Underlying costs billed separately",
  pricing_cost_bundled: "Underlying costs bundled into merchant pricing",
  pricing_cost_mixed: "Underlying-cost treatment varies by scope",
  pricing_no_active: "No active processing observed",
  pricing_unknown: "Not confirmed",
  pricing_shape_uniform_flat: "Uniform flat percentage",
  pricing_shape_scope_flat: "Scope-specific flat percentage",
  pricing_shape_tier_ladder: "Qualification-tier schedule",
  pricing_shape_rate_item: "Rate plus per-item pricing",
  pricing_shape_fixed_variable: "Fixed plus variable pricing",
  pricing_shape_subscription: "Subscription or membership pricing",
  pricing_shape_minimum: "Minimum-based pricing",
  pricing_shape_composite: "Multiple pricing components",
  pricing_shape_custom: "Other supported pricing structure",
  pricing_scope_uniform: "Uniform across the admitted scope",
  pricing_scope_exceptions: "Uniform with explicit exceptions",
  pricing_scope_specific: "Varies by admitted scope",
  composition_title: "Where the fees went",
  composition_partial: "The displayed categories reconcile, but source detail is incomplete.",
  composition_unreconciled: "The available fee detail does not reconcile to the statement total. Percentage composition is withheld.",
  category_interchange: "Interchange",
  category_network: "Network / Card Brand",
  category_processor: "Processor-controlled pricing",
  category_services: "Services / Admin",
  category_third_party: "Third-party / Equipment",
  category_operational: "Operational / Penalty",
  category_taxes: "Processing-fee taxes",
  category_other: "Other source-grounded fees",
  category_unresolved: "Unresolved",
  fee_credit_offset: "Fee credits",
  inventory_title_complete: "Complete fee inventory",
  inventory_title_available: "Available fee inventory",
  inventory_title_partial: "Partial fee inventory",
  inventory_item_fee: "Statement fee item",
  inventory_item_credit: "Statement fee credit",
  owner_not_confirmed: "Owner or control not confirmed",
  control_confirmed: "A control role is confirmed",
  attention_title: "Merchant Attention",
  theme_pricing_structure_title: "Review the confirmed pricing structure",
  theme_pricing_structure_body: "The statement supports a pricing-structure observation that may affect how costs are interpreted.",
  theme_major_driver_title: "A processing-mix factor is material",
  theme_major_driver_body: "A source-supported transaction population contributes materially to the observed cost structure.",
  theme_control_title: "Cost control remains unresolved",
  theme_control_body: "The charge is observed, but the evidence does not establish who controls or can change it.",
  theme_refund_title: "Refund economics need review",
  theme_refund_body: "The statement supports refund activity, while some return or pricing treatment remains unresolved.",
  theme_service_title: "Review an account service charge",
  theme_service_body: "A service charge is observed, but usage or contract terms may require confirmation.",
  theme_operational_title: "Review an operational signal",
  theme_operational_body: "The statement shows an operational pattern without proving fault, causation, or savings.",
  theme_dispute_title: "Dispute activity needs context",
  theme_dispute_body: "Dispute-related activity is observed without a compatible basis for a risk conclusion.",
  theme_program_title: "Review merchant pricing-program flows",
  theme_program_body: "Program fees and consumer-facing economics must be considered together before drawing a net-benefit conclusion.",
  theme_off_statement_title: "An off-statement document may be needed",
  theme_off_statement_body: "The statement alone cannot establish the complete economics of this item.",
  theme_positive_title: "A supported control is present",
  theme_positive_body: "The available evidence supports a positive financial or operational control without implying broader account health.",
  theme_other_title: "Review a supported economic question",
  theme_other_body: "The statement supports an economic question that should remain separate from unsupported savings or fault claims.",
  questions_title: "Questions to resolve",
  question_known: "The statement provides a confirmed starting point.",
  question_external_rule: "A current network or processor rule is not yet confirmed.",
  question_pricing_document: "The current pricing or merchant agreement is needed to confirm this conclusion.",
  question_processor_explanation: "The statement does not explain the role of this charge or condition.",
  question_more_history: "Additional statement history is needed to establish recurrence or a trend.",
  question_template_admission: "The statement format does not prove all required population semantics.",
  question_external_source: "An authoritative external source is required before this conclusion can be made.",
  question_knowledge_conflict: "Available authoritative information conflicts and must be resolved before use.",
  question_synthesis_coverage: "The available analysis has not positively established sufficient thematic coverage.",
  question_next_step_document: "Review the applicable pricing schedule or merchant agreement.",
  question_next_step_processor: "Ask what the charge or condition represents and which document controls it.",
  question_next_step_history: "Compare another complete statement period using the same canonical fields.",
  question_next_step_review: "Keep this item open until the required evidence is available.",
  potential_reduction: "Potential reduction",
  potential_reduction_range: "Potential reduction range",
  amount_under_review: "Amount under review",
  action_title: "Action Toolkit",
  action_pricing_review: "Review the current pricing terms",
  action_configuration_review: "Review the acceptance or account configuration",
  action_service_review: "Confirm service use and contract terms",
  action_documentation: "Gather the controlling document",
  action_process_review: "Review the operating process",
  action_monitoring: "Create a future-period comparison baseline",
  call_pricing: "Ask the processor to review the current pricing schedule and explain which terms apply.",
  call_configuration: "Ask how the current acceptance configuration affects this item and what documented options exist.",
  call_service: "Ask what the service provides, whether it is optional, and which agreement controls it.",
  call_documentation: "Ask which document or schedule controls this charge or condition.",
  call_process: "Ask which operational condition produces this item and how the process is documented.",
  call_monitoring: "Ask how the processed-sales, fee, and transaction-count fields should be compared across future statements.",
  compare_months_title: "Compare other months",
  compare_months_body: "A second statement can help establish recurrence and change over time. It is not required for this free analysis.",
  compare_months_cta: "Compare other months",
  recovery_cta: "Use a complete statement",
  methodology_title: "Why we reached this conclusion",
  method_one_statement: "This report analyzes one merchant-processing statement.",
  method_net_submitted: "Processed sales use the canonical net-submitted card population.",
  method_rate_denominator: "Effective rate uses statement processing fees divided by canonical net-submitted card volume.",
  method_reconciled: "Displayed processing costs reconcile to the authoritative statement fee total.",
  method_partial: "The displayed processing costs reconcile, but available category detail is incomplete.",
  method_unreconciled: "Available processing-cost detail does not reconcile, so composition percentages are withheld.",
  method_no_external_links: "No external research source is used as customer-facing evidence in this report.",
  method_open_questions: "Material unresolved questions remain separate from confirmed findings and impact.",
  evidence_page: "Statement page",
  evidence_summary: "Statement summary",
  evidence_sales: "Sales activity",
  evidence_funding: "Funding activity",
  evidence_fees: "Fees",
  evidence_interchange: "Interchange detail",
  evidence_card_activity: "Card activity",
  evidence_adjustments: "Adjustments",
  evidence_chargebacks: "Chargebacks",
  evidence_account: "Account information",
  evidence_notices: "Statement notices",
  evidence_other: "Statement evidence",
};

export function rhCopy(code: RhCopyCode): RhCustomerCopy {
  const text = RH_COPY_REGISTRY[code];
  if (!text) throw new Error(`RH_UNKNOWN_COPY_CODE:${String(code)}`);
  return { code, text };
}
