import type { ReferenceRateCatalogRow } from "./referenceRateCatalog.js";

const WELLS_FARGO_2026_SOURCE = "data/reference-rate-sources/wells-fargo-merchant-passthrough-fees-2026-04.pdf";
const WELLS_FARGO_2026_NAME = "Wells Fargo Merchant Services Payment Network Pass-Through Fee Schedule";
const WELLS_FARGO_2026_VERSION = "Effective April 2026; WFMS-204 03/26";

function networkTrueRow(row: Omit<ReferenceRateCatalogRow, "sourceType" | "sourceName" | "sourceVersion" | "sourceFile" | "costProvableFromRateMatch" | "region" | "rateScope" | "atCostProofEligible" | "confidence">): ReferenceRateCatalogRow {
  return {
    ...row,
    sourceType: "acquirer_schedule",
    sourceName: WELLS_FARGO_2026_NAME,
    sourceVersion: WELLS_FARGO_2026_VERSION,
    sourceFile: WELLS_FARGO_2026_SOURCE,
    costProvableFromRateMatch: true,
    region: "US",
    rateScope: "network_true",
    atCostProofEligible: true,
    confidence: "verified",
  };
}

export const wellsFargo2026ReferenceRateCatalog: ReferenceRateCatalogRow[] = [
  networkTrueRow({
    feeCode: "VISA_ASSESSMENT_CREDIT_US_2026_04",
    aliases: ["VISA ASSESSMENT FEE", "CR DUES AND ASSESS"],
    network: "VISA",
    cardProduct: "credit",
    feeFamily: "assessment",
    feeCategory: "card_brand_assessment",
    rateBasis: "percent_of_volume",
    percentRate: 0.0014,
    perItemFee: null,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Visa U.S. acquirer service fee for credit sale transactions.",
  }),
  networkTrueRow({
    feeCode: "VISA_ASSESSMENT_DEBIT_PREPAID_US_2026_04",
    aliases: ["VISA ASSESSMENT FEE DB", "DB DUES AND ASSESS"],
    network: "VISA",
    cardProduct: "debit_prepaid",
    feeFamily: "assessment",
    feeCategory: "card_brand_assessment",
    rateBasis: "percent_of_volume",
    percentRate: 0.0013,
    perItemFee: null,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Visa U.S. acquirer service fee for debit and prepaid sale transactions.",
  }),
  networkTrueRow({
    feeCode: "VISA_APF_CREDIT_US_2026_04",
    aliases: ["VI NTWK ACQ PROC FEE", "ACQR PROCESSOR FEES", "ACOR PROCESSOR FEES"],
    network: "VISA",
    cardProduct: "credit",
    feeFamily: "network_per_item",
    feeCategory: "card_brand_network_fee",
    rateBasis: "per_auth",
    percentRate: null,
    perItemFee: 0.0195,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Visa authorization processing fee for U.S. credit authorizations.",
  }),
  networkTrueRow({
    feeCode: "VISA_APF_DEBIT_PREPAID_US_2026_04",
    aliases: ["VI NTWK ACQ RPOC FEE", "ACQR PROCESSOR FEES"],
    network: "VISA",
    cardProduct: "debit_prepaid",
    feeFamily: "network_per_item",
    feeCategory: "card_brand_network_fee",
    rateBasis: "per_auth",
    percentRate: null,
    perItemFee: 0.0155,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Visa authorization processing fee for U.S. debit and prepaid authorizations.",
  }),
  networkTrueRow({
    feeCode: "VISA_INTL_SERVICE_BASE_US_2026_04",
    aliases: ["VISA INTL SERVICE FEE BASE", "VISA INTERNATIONAL SERVICE FEE BASE"],
    network: "VISA",
    cardProduct: null,
    feeFamily: "assessment",
    feeCategory: "card_brand_assessment",
    rateBasis: "percent_of_volume",
    percentRate: 0.01,
    perItemFee: null,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Visa international service fee base rate.",
  }),
  networkTrueRow({
    feeCode: "VISA_INTL_ACQUIRER_US_2026_04",
    aliases: ["VS INTL ACQ FEE", "VISA INTERNATIONAL ACQUIRER FEE"],
    network: "VISA",
    cardProduct: null,
    feeFamily: "assessment",
    feeCategory: "card_brand_assessment",
    rateBasis: "percent_of_volume",
    percentRate: 0.0045,
    perItemFee: null,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Visa international acquirer fee.",
  }),
  networkTrueRow({
    feeCode: "VISA_BASE_II_FILE_TRANSMISSION_US_2026_04",
    aliases: ["VI BASE II SYSTEM FILE FEE", "FILE TRANSMISSION FEE"],
    network: "VISA",
    cardProduct: null,
    feeFamily: "network_per_item",
    feeCategory: "card_brand_network_fee",
    rateBasis: "per_item",
    percentRate: null,
    perItemFee: 0.0025,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Visa Base II system file transmission fee.",
  }),
  networkTrueRow({
    feeCode: "VISA_COMMERCIAL_SOLUTIONS_US_2026_04",
    aliases: ["VI COMMERCIAL SOLUTIONS FEE", "VI-COMMERCIAL SOLUTIONS FEE"],
    network: "VISA",
    cardProduct: "commercial",
    feeFamily: "assessment",
    feeCategory: "card_brand_assessment",
    rateBasis: "percent_of_volume",
    percentRate: 0.0001,
    perItemFee: null,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Visa commercial solutions fee.",
  }),
  networkTrueRow({
    feeCode: "MC_ASSESSMENT_COMBINED_US_2026_04",
    aliases: ["MASTERCARD ASSESSMENT FEE"],
    network: "MASTERCARD",
    cardProduct: null,
    feeFamily: "assessment",
    feeCategory: "card_brand_assessment",
    rateBasis: "percent_of_volume",
    percentRate: 0.001475,
    perItemFee: null,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Mastercard acquirer brand volume assessment, comprised of brand volume plus annual acquirer license components in this schedule.",
  }),
  networkTrueRow({
    feeCode: "MC_NABU_AUTH_US_2026_04",
    aliases: ["MC NETWORK ACCESS AUTH FEE", "NABU FEES"],
    network: "MASTERCARD",
    cardProduct: null,
    feeFamily: "network_per_item",
    feeCategory: "card_brand_network_fee",
    rateBasis: "per_auth",
    percentRate: null,
    perItemFee: 0.0195,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Mastercard Network Access Brand Usage authorization fee.",
  }),
  networkTrueRow({
    feeCode: "MC_NABU_SETTLEMENT_US_2026_04",
    aliases: ["MC NTWRK ACCESS SETTLEMENT FEE"],
    network: "MASTERCARD",
    cardProduct: null,
    feeFamily: "network_per_item",
    feeCategory: "card_brand_network_fee",
    rateBasis: "per_item",
    percentRate: null,
    perItemFee: 0.0195,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Mastercard Network Access Brand Usage settlement fee.",
  }),
  networkTrueRow({
    feeCode: "MC_MERCHANT_LOCATION_US_2026_04",
    aliases: ["MC MERCH MONTHLY LOCATION", "MC MONTHLY LOCATION FEE", "MC LOCATION FEE"],
    network: "MASTERCARD",
    cardProduct: null,
    feeFamily: "network_per_item",
    feeCategory: "card_brand_network_fee",
    rateBasis: "flat_monthly",
    percentRate: null,
    perItemFee: null,
    flatFee: 1.25,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Mastercard monthly merchant location fee.",
  }),
  networkTrueRow({
    feeCode: "MC_AUTH_US_2026_04",
    aliases: ["MC AUTH"],
    network: "MASTERCARD",
    cardProduct: null,
    feeFamily: "network_per_item",
    feeCategory: "card_brand_network_fee",
    rateBasis: "per_auth",
    percentRate: null,
    perItemFee: 0.002294,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Mastercard authorization fee.",
  }),
  networkTrueRow({
    feeCode: "MC_CLEARING_US_2026_04",
    aliases: ["MC CLEARING"],
    network: "MASTERCARD",
    cardProduct: null,
    feeFamily: "network_per_item",
    feeCategory: "card_brand_network_fee",
    rateBasis: "per_item",
    percentRate: null,
    perItemFee: 0.002294,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Mastercard clearing fee.",
  }),
  networkTrueRow({
    feeCode: "DISCOVER_ASSESSMENT_US_2026_04",
    aliases: ["DISCOVER DUES ASSESSMENT FEE", "DISCOVER DUES/ASSESSMENT FEE"],
    network: "DISCOVER",
    cardProduct: null,
    feeFamily: "assessment",
    feeCategory: "card_brand_assessment",
    rateBasis: "percent_of_volume",
    percentRate: 0.0014,
    perItemFee: null,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Discover assessments.",
  }),
  networkTrueRow({
    feeCode: "DISCOVER_DATA_USAGE_US_2026_04",
    aliases: ["DISCOVER DATA USAGE FEE"],
    network: "DISCOVER",
    cardProduct: null,
    feeFamily: "network_per_item",
    feeCategory: "card_brand_network_fee",
    rateBasis: "per_item",
    percentRate: null,
    perItemFee: 0.0025,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Discover data usage fee.",
  }),
  networkTrueRow({
    feeCode: "DISCOVER_NETWORK_AUTH_US_2026_04",
    aliases: ["NETWORK AUTHORIZATION"],
    network: "DISCOVER",
    cardProduct: null,
    feeFamily: "network_per_item",
    feeCategory: "card_brand_network_fee",
    rateBasis: "per_auth",
    percentRate: null,
    perItemFee: 0.019,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "Discover network authorization fee.",
  }),
  networkTrueRow({
    feeCode: "AMEX_NETWORK_ASSESSMENT_US_2026_04",
    aliases: ["AXP NETWORK ASSESSMENT FEE", "AMERICAN EXPRESS NETWORK ASSESSMENT FEE"],
    network: "AMEX",
    cardProduct: null,
    feeFamily: "assessment",
    feeCategory: "card_brand_assessment",
    rateBasis: "percent_of_volume",
    percentRate: 0.00165,
    perItemFee: null,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "American Express network assessment fee.",
  }),
  networkTrueRow({
    feeCode: "AMEX_ACQUIRER_US_2026_04",
    aliases: ["AXP ACQUIRER", "AMERICAN EXPRESS ACQUIRER FEE"],
    network: "AMEX",
    cardProduct: null,
    feeFamily: "network_per_item",
    feeCategory: "card_brand_network_fee",
    rateBasis: "per_item",
    percentRate: null,
    perItemFee: 0.02,
    flatFee: null,
    minimumFee: null,
    maximumFee: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
    matchTolerance: null,
    notes: "American Express acquirer fee.",
  }),
];
